# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from biolevate_client.models.agent_completion_config import AgentCompletionConfig
from biolevate_client.models.agent_input import AgentInput
from biolevate_client.models.files_input import FilesInput
from typing import Optional, Set
from typing_extensions import Self

class AgentJobInputs(BaseModel):
    """
    AgentJobInputs
    """ # noqa: E501
    message: Optional[StrictStr] = None
    messages: Optional[List[AgentInput]] = None
    files: Optional[FilesInput] = None
    output_model_schema: Optional[Dict[str, Any]] = Field(default=None, alias="outputModelSchema")
    completion_config: Optional[AgentCompletionConfig] = Field(default=None, alias="completionConfig")
    max_iterations: Optional[StrictInt] = Field(default=None, alias="maxIterations")
    conversation_id: Optional[UUID] = Field(default=None, alias="conversationId")
    __properties: ClassVar[List[str]] = ["message", "messages", "files", "outputModelSchema", "completionConfig", "maxIterations", "conversationId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentJobInputs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of files
        if self.files:
            _dict['files'] = self.files.to_dict()
        # override the default output from pydantic by calling `to_dict()` of completion_config
        if self.completion_config:
            _dict['completionConfig'] = self.completion_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentJobInputs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "messages": [AgentInput.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "files": FilesInput.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "outputModelSchema": obj.get("outputModelSchema"),
            "completionConfig": AgentCompletionConfig.from_dict(obj["completionConfig"]) if obj.get("completionConfig") is not None else None,
            "maxIterations": obj.get("maxIterations"),
            "conversationId": obj.get("conversationId")
        })
        return _obj


