from enum import Enum


class CollectionIdEntityType(str, Enum):
    ANNOTATION = "ANNOTATION"
    BIBLIO_SEARCH = "BIBLIO_SEARCH"
    COLLECTION = "COLLECTION"
    COLLECTION_DERIVATION = "COLLECTION_DERIVATION"
    COLLECTION_VIEW = "COLLECTION_VIEW"
    COMMENT = "COMMENT"
    COMMENT_THREAD = "COMMENT_THREAD"
    CONCEPT_NOTE = "CONCEPT_NOTE"
    EDITABLE_DOCUMENT = "EDITABLE_DOCUMENT"
    FILE = "FILE"
    FORGE_WORKFLOW = "FORGE_WORKFLOW"
    INSIGHT = "INSIGHT"
    INSIGHTS_TABLE_CONFIG = "INSIGHTS_TABLE_CONFIG"
    INSIGHTS_TABLE_TEMPLATE = "INSIGHTS_TABLE_TEMPLATE"
    INSIGHT_CELL_FILTER = "INSIGHT_CELL_FILTER"
    INSIGHT_CELL_FORMAT = "INSIGHT_CELL_FORMAT"
    INSIGHT_CELL_SORTING = "INSIGHT_CELL_SORTING"
    INSIGHT_GROUP = "INSIGHT_GROUP"
    JOB = "JOB"
    MILESTONE = "MILESTONE"
    POLICY = "POLICY"
    PRESET = "PRESET"
    PROCESSOR = "PROCESSOR"
    PROJECT = "PROJECT"
    PROVIDER = "PROVIDER"
    REVIEW = "REVIEW"
    REVIEW_REQUEST = "REVIEW_REQUEST"
    RIS_IMPORT_JOB = "RIS_IMPORT_JOB"
    SEARCH_DOWNLOAD = "SEARCH_DOWNLOAD"
    SEARCH_REMOVAL = "SEARCH_REMOVAL"
    SMART_REVIEW = "SMART_REVIEW"
    SUB_COLLECTION_JOB = "SUB_COLLECTION_JOB"

    def __str__(self) -> str:
        return str(self.value)
