# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.annotation_id import AnnotationId
from biolevate_client.models.elise_annotation_data import EliseAnnotationData
from biolevate_client.models.entity_id import EntityId
from biolevate_client.models.user_id import UserId
from typing import Optional, Set
from typing_extensions import Self

class EliseAnnotation(BaseModel):
    """
    EliseAnnotation
    """ # noqa: E501
    id: Optional[AnnotationId] = None
    created_time: Optional[StrictInt] = Field(default=None, alias="createdTime")
    owner: Optional[UserId] = None
    space: Optional[EntityId] = None
    data: Optional[EliseAnnotationData] = None
    type: Optional[StrictStr] = None
    modified_time: Optional[StrictInt] = Field(default=None, alias="modifiedTime")
    last_modifier: Optional[UserId] = Field(default=None, alias="lastModifier")
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "createdTime", "owner", "space", "data", "type", "modifiedTime", "lastModifier", "status"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DOCUMENT_STATEMENT', 'WEB_STATEMENT', 'ENTIRE_DOCUMENT_STATEMENT', 'EXTERNAL_DOCUMENT_STATEMENT', 'KNOWLEDGE_STATEMENT', 'REVIEW_STATEMENT', 'UNRECOGNIZED']):
            raise ValueError("must be one of enum values ('DOCUMENT_STATEMENT', 'WEB_STATEMENT', 'ENTIRE_DOCUMENT_STATEMENT', 'EXTERNAL_DOCUMENT_STATEMENT', 'KNOWLEDGE_STATEMENT', 'REVIEW_STATEMENT', 'UNRECOGNIZED')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['VALID', 'NOTVALID']):
            raise ValueError("must be one of enum values ('VALID', 'NOTVALID')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseAnnotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of space
        if self.space:
            _dict['space'] = self.space.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_modifier
        if self.last_modifier:
            _dict['lastModifier'] = self.last_modifier.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseAnnotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": AnnotationId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "createdTime": obj.get("createdTime"),
            "owner": UserId.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "space": EntityId.from_dict(obj["space"]) if obj.get("space") is not None else None,
            "data": EliseAnnotationData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "type": obj.get("type"),
            "modifiedTime": obj.get("modifiedTime"),
            "lastModifier": UserId.from_dict(obj["lastModifier"]) if obj.get("lastModifier") is not None else None,
            "status": obj.get("status")
        })
        return _obj


