# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EliseEntityColumnInput(BaseModel):
    """
    EliseEntityColumnInput
    """ # noqa: E501
    key: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    role: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    allowed_values: Optional[List[StrictStr]] = Field(default=None, alias="allowedValues")
    is_row_key: Optional[StrictBool] = Field(default=None, alias="isRowKey")
    __properties: ClassVar[List[str]] = ["key", "label", "type", "role", "description", "allowedValues", "isRowKey"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ENTITY_COLUMN_TYPE_UNSPECIFIED', 'ENTITY_COLUMN_TYPE_STRING', 'ENTITY_COLUMN_TYPE_INT', 'ENTITY_COLUMN_TYPE_FLOAT', 'ENTITY_COLUMN_TYPE_BOOL', 'UNRECOGNIZED']):
            raise ValueError("must be one of enum values ('ENTITY_COLUMN_TYPE_UNSPECIFIED', 'ENTITY_COLUMN_TYPE_STRING', 'ENTITY_COLUMN_TYPE_INT', 'ENTITY_COLUMN_TYPE_FLOAT', 'ENTITY_COLUMN_TYPE_BOOL', 'UNRECOGNIZED')")
        return value

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ENTITY_COLUMN_ROLE_UNSPECIFIED', 'ENTITY_COLUMN_ROLE_IDENTIFIER', 'ENTITY_COLUMN_ROLE_LABEL', 'ENTITY_COLUMN_ROLE_GROUP', 'ENTITY_COLUMN_ROLE_TIMEPOINT', 'ENTITY_COLUMN_ROLE_VALUE', 'ENTITY_COLUMN_ROLE_UNIT', 'ENTITY_COLUMN_ROLE_DEFINITION', 'ENTITY_COLUMN_ROLE_COMMENT', 'UNRECOGNIZED']):
            raise ValueError("must be one of enum values ('ENTITY_COLUMN_ROLE_UNSPECIFIED', 'ENTITY_COLUMN_ROLE_IDENTIFIER', 'ENTITY_COLUMN_ROLE_LABEL', 'ENTITY_COLUMN_ROLE_GROUP', 'ENTITY_COLUMN_ROLE_TIMEPOINT', 'ENTITY_COLUMN_ROLE_VALUE', 'ENTITY_COLUMN_ROLE_UNIT', 'ENTITY_COLUMN_ROLE_DEFINITION', 'ENTITY_COLUMN_ROLE_COMMENT', 'UNRECOGNIZED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseEntityColumnInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseEntityColumnInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "label": obj.get("label"),
            "type": obj.get("type"),
            "role": obj.get("role"),
            "description": obj.get("description"),
            "allowedValues": obj.get("allowedValues"),
            "isRowKey": obj.get("isRowKey")
        })
        return _obj


