# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.expected_answer_type_dto import ExpectedAnswerTypeDto
from typing import Optional, Set
from typing_extensions import Self

class EliseQuestionInput(BaseModel):
    """
    EliseQuestionInput
    """ # noqa: E501
    id: Optional[StrictStr] = None
    question: Optional[StrictStr] = None
    answer_type: Optional[ExpectedAnswerTypeDto] = Field(default=None, alias="answerType")
    guidelines: Optional[StrictStr] = None
    expected_answer: Optional[StrictStr] = Field(default=None, alias="expectedAnswer")
    input_question_ids: Optional[List[StrictStr]] = Field(default=None, alias="inputQuestionIds")
    __properties: ClassVar[List[str]] = ["id", "question", "answerType", "guidelines", "expectedAnswer", "inputQuestionIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseQuestionInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of answer_type
        if self.answer_type:
            _dict['answerType'] = self.answer_type.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseQuestionInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "question": obj.get("question"),
            "answerType": ExpectedAnswerTypeDto.from_dict(obj["answerType"]) if obj.get("answerType") is not None else None,
            "guidelines": obj.get("guidelines"),
            "expectedAnswer": obj.get("expectedAnswer"),
            "inputQuestionIds": obj.get("inputQuestionIds")
        })
        return _obj


