from enum import Enum


class EliseAnnotationType(str, Enum):
    DOCUMENT_STATEMENT = "DOCUMENT_STATEMENT"
    ENTIRE_DOCUMENT_STATEMENT = "ENTIRE_DOCUMENT_STATEMENT"
    EXTERNAL_DOCUMENT_STATEMENT = "EXTERNAL_DOCUMENT_STATEMENT"
    KNOWLEDGE_STATEMENT = "KNOWLEDGE_STATEMENT"
    REVIEW_STATEMENT = "REVIEW_STATEMENT"
    UNRECOGNIZED = "UNRECOGNIZED"
    WEB_STATEMENT = "WEB_STATEMENT"

    def __str__(self) -> str:
        return str(self.value)
