# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.collection_id import CollectionId
from biolevate_client.models.collection_view_id import CollectionViewId
from biolevate_client.models.policy_id import PolicyId
from biolevate_client.models.user_id import UserId
from typing import Optional, Set
from typing_extensions import Self

class EliseCollectionInfo(BaseModel):
    """
    EliseCollectionInfo
    """ # noqa: E501
    id: Optional[CollectionId] = None
    created_time: Optional[StrictInt] = Field(default=None, alias="createdTime")
    owner: Optional[UserId] = None
    policy: Optional[PolicyId] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    icon: Optional[StrictStr] = None
    owner_first_name: Optional[StrictStr] = Field(default=None, alias="ownerFirstName")
    owner_last_name: Optional[StrictStr] = Field(default=None, alias="ownerLastName")
    owner_email: Optional[StrictStr] = Field(default=None, alias="ownerEmail")
    owner_avatar_url: Optional[StrictStr] = Field(default=None, alias="ownerAvatarUrl")
    files_count: Optional[StrictInt] = Field(default=None, alias="filesCount")
    derived_from_collection_id: Optional[CollectionId] = Field(default=None, alias="derivedFromCollectionId")
    derived_from_collection_name: Optional[StrictStr] = Field(default=None, alias="derivedFromCollectionName")
    derived_from_view_id: Optional[CollectionViewId] = Field(default=None, alias="derivedFromViewId")
    derived_from_view_name: Optional[StrictStr] = Field(default=None, alias="derivedFromViewName")
    chained: Optional[StrictBool] = None
    derived_to_collection_id: Optional[CollectionId] = Field(default=None, alias="derivedToCollectionId")
    derived_to_collection_name: Optional[StrictStr] = Field(default=None, alias="derivedToCollectionName")
    __properties: ClassVar[List[str]] = ["id", "createdTime", "owner", "policy", "name", "description", "icon", "ownerFirstName", "ownerLastName", "ownerEmail", "ownerAvatarUrl", "filesCount", "derivedFromCollectionId", "derivedFromCollectionName", "derivedFromViewId", "derivedFromViewName", "chained", "derivedToCollectionId", "derivedToCollectionName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseCollectionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of derived_from_collection_id
        if self.derived_from_collection_id:
            _dict['derivedFromCollectionId'] = self.derived_from_collection_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of derived_from_view_id
        if self.derived_from_view_id:
            _dict['derivedFromViewId'] = self.derived_from_view_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of derived_to_collection_id
        if self.derived_to_collection_id:
            _dict['derivedToCollectionId'] = self.derived_to_collection_id.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseCollectionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": CollectionId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "createdTime": obj.get("createdTime"),
            "owner": UserId.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "policy": PolicyId.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "name": obj.get("name"),
            "description": obj.get("description"),
            "icon": obj.get("icon"),
            "ownerFirstName": obj.get("ownerFirstName"),
            "ownerLastName": obj.get("ownerLastName"),
            "ownerEmail": obj.get("ownerEmail"),
            "ownerAvatarUrl": obj.get("ownerAvatarUrl"),
            "filesCount": obj.get("filesCount"),
            "derivedFromCollectionId": CollectionId.from_dict(obj["derivedFromCollectionId"]) if obj.get("derivedFromCollectionId") is not None else None,
            "derivedFromCollectionName": obj.get("derivedFromCollectionName"),
            "derivedFromViewId": CollectionViewId.from_dict(obj["derivedFromViewId"]) if obj.get("derivedFromViewId") is not None else None,
            "derivedFromViewName": obj.get("derivedFromViewName"),
            "chained": obj.get("chained"),
            "derivedToCollectionId": CollectionId.from_dict(obj["derivedToCollectionId"]) if obj.get("derivedToCollectionId") is not None else None,
            "derivedToCollectionName": obj.get("derivedToCollectionName")
        })
        return _obj


