# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from biolevate_client.models.elise_document_statement import EliseDocumentStatement
from biolevate_client.models.elise_external_document_statement import EliseExternalDocumentStatement
from biolevate_client.models.elise_full_document_statement import EliseFullDocumentStatement
from biolevate_client.models.elise_knowledge_statement import EliseKnowledgeStatement
from biolevate_client.models.elise_review_comment import EliseReviewComment
from biolevate_client.models.elise_web_statement import EliseWebStatement
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ELISEANNOTATIONDATA_ONE_OF_SCHEMAS = ["EliseDocumentStatement", "EliseExternalDocumentStatement", "EliseFullDocumentStatement", "EliseKnowledgeStatement", "EliseReviewComment", "EliseWebStatement"]

class EliseAnnotationData(BaseModel):
    """
    EliseAnnotationData
    """
    # data type: EliseDocumentStatement
    oneof_schema_1_validator: Optional[EliseDocumentStatement] = None
    # data type: EliseExternalDocumentStatement
    oneof_schema_2_validator: Optional[EliseExternalDocumentStatement] = None
    # data type: EliseFullDocumentStatement
    oneof_schema_3_validator: Optional[EliseFullDocumentStatement] = None
    # data type: EliseKnowledgeStatement
    oneof_schema_4_validator: Optional[EliseKnowledgeStatement] = None
    # data type: EliseReviewComment
    oneof_schema_5_validator: Optional[EliseReviewComment] = None
    # data type: EliseWebStatement
    oneof_schema_6_validator: Optional[EliseWebStatement] = None
    actual_instance: Optional[Union[EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement]] = None
    one_of_schemas: Set[str] = { "EliseDocumentStatement", "EliseExternalDocumentStatement", "EliseFullDocumentStatement", "EliseKnowledgeStatement", "EliseReviewComment", "EliseWebStatement" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EliseAnnotationData.model_construct()
        error_messages = []
        match = 0
        # validate data type: EliseDocumentStatement
        if not isinstance(v, EliseDocumentStatement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseDocumentStatement`")
        else:
            match += 1
        # validate data type: EliseExternalDocumentStatement
        if not isinstance(v, EliseExternalDocumentStatement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseExternalDocumentStatement`")
        else:
            match += 1
        # validate data type: EliseFullDocumentStatement
        if not isinstance(v, EliseFullDocumentStatement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseFullDocumentStatement`")
        else:
            match += 1
        # validate data type: EliseKnowledgeStatement
        if not isinstance(v, EliseKnowledgeStatement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseKnowledgeStatement`")
        else:
            match += 1
        # validate data type: EliseReviewComment
        if not isinstance(v, EliseReviewComment):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseReviewComment`")
        else:
            match += 1
        # validate data type: EliseWebStatement
        if not isinstance(v, EliseWebStatement):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EliseWebStatement`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EliseAnnotationData with oneOf schemas: EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EliseAnnotationData with oneOf schemas: EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EliseDocumentStatement
        try:
            instance.actual_instance = EliseDocumentStatement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EliseExternalDocumentStatement
        try:
            instance.actual_instance = EliseExternalDocumentStatement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EliseFullDocumentStatement
        try:
            instance.actual_instance = EliseFullDocumentStatement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EliseKnowledgeStatement
        try:
            instance.actual_instance = EliseKnowledgeStatement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EliseReviewComment
        try:
            instance.actual_instance = EliseReviewComment.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EliseWebStatement
        try:
            instance.actual_instance = EliseWebStatement.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EliseAnnotationData with oneOf schemas: EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EliseAnnotationData with oneOf schemas: EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EliseDocumentStatement, EliseExternalDocumentStatement, EliseFullDocumentStatement, EliseKnowledgeStatement, EliseReviewComment, EliseWebStatement]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


