# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.elise_annotation_config import EliseAnnotationConfig
from biolevate_client.models.elise_document_statement_all_of_positions import EliseDocumentStatementAllOfPositions
from typing import Optional, Set
from typing_extensions import Self

class EliseReviewComment(EliseAnnotationConfig):
    """
    EliseReviewComment
    """ # noqa: E501
    content: Optional[StrictStr] = None
    document_name: Optional[StrictStr] = Field(default=None, alias="documentName")
    document_id: Optional[StrictStr] = Field(default=None, alias="documentId")
    positions: Optional[List[EliseDocumentStatementAllOfPositions]] = None
    __properties: ClassVar[List[str]] = ["type", "content", "documentName", "documentId", "positions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseReviewComment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in positions (list)
        _items = []
        if self.positions:
            for _item_positions in self.positions:
                if _item_positions:
                    _items.append(_item_positions.to_dict())
            _dict['positions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseReviewComment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "content": obj.get("content"),
            "documentName": obj.get("documentName"),
            "documentId": obj.get("documentId"),
            "positions": [EliseDocumentStatementAllOfPositions.from_dict(_item) for _item in obj["positions"]] if obj.get("positions") is not None else None
        })
        return _obj


