# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.file_id import FileId
from biolevate_client.models.lib_item_indexation_infos import LibItemIndexationInfos
from biolevate_client.models.policy_id import PolicyId
from biolevate_client.models.provider_id import ProviderId
from biolevate_client.models.user_id import UserId
from typing import Optional, Set
from typing_extensions import Self

class EliseFileInfo(BaseModel):
    """
    EliseFileInfo
    """ # noqa: E501
    id: Optional[FileId] = None
    created_time: Optional[StrictInt] = Field(default=None, alias="createdTime")
    owner: Optional[UserId] = None
    policy: Optional[PolicyId] = None
    provider_id: Optional[ProviderId] = Field(default=None, alias="providerId")
    name: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    checksum: Optional[StrictStr] = None
    media_type: Optional[StrictStr] = Field(default=None, alias="mediaType")
    extension: Optional[StrictStr] = None
    indexed: Optional[StrictBool] = None
    match_computed: Optional[StrictBool] = Field(default=None, alias="matchComputed")
    display_name: Optional[StrictStr] = Field(default=None, alias="displayName")
    db_name: Optional[StrictStr] = Field(default=None, alias="dbName")
    last_indexation_infos: Optional[LibItemIndexationInfos] = Field(default=None, alias="lastIndexationInfos")
    owner_first_name: Optional[StrictStr] = Field(default=None, alias="ownerFirstName")
    owner_last_name: Optional[StrictStr] = Field(default=None, alias="ownerLastName")
    owner_email: Optional[StrictStr] = Field(default=None, alias="ownerEmail")
    owner_avatar_url: Optional[StrictStr] = Field(default=None, alias="ownerAvatarUrl")
    provider_name: Optional[StrictStr] = Field(default=None, alias="providerName")
    additional_info: Optional[Dict[str, Any]] = Field(default=None, alias="additionalInfo")
    description: Optional[StrictStr] = None
    authors: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    additional_infos: Optional[Dict[str, Any]] = Field(default=None, alias="additionalInfos")
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "createdTime", "owner", "policy", "providerId", "name", "path", "size", "checksum", "mediaType", "extension", "indexed", "matchComputed", "displayName", "dbName", "lastIndexationInfos", "ownerFirstName", "ownerLastName", "ownerEmail", "ownerAvatarUrl", "providerName", "additionalInfo", "description", "authors", "title", "additionalInfos", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['FILE', 'FOLDER', 'ELISE_FILE']):
            raise ValueError("must be one of enum values ('FILE', 'FOLDER', 'ELISE_FILE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EliseFileInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of provider_id
        if self.provider_id:
            _dict['providerId'] = self.provider_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_indexation_infos
        if self.last_indexation_infos:
            _dict['lastIndexationInfos'] = self.last_indexation_infos.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EliseFileInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": FileId.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "createdTime": obj.get("createdTime"),
            "owner": UserId.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "policy": PolicyId.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "providerId": ProviderId.from_dict(obj["providerId"]) if obj.get("providerId") is not None else None,
            "name": obj.get("name"),
            "path": obj.get("path"),
            "size": obj.get("size"),
            "checksum": obj.get("checksum"),
            "mediaType": obj.get("mediaType"),
            "extension": obj.get("extension"),
            "indexed": obj.get("indexed"),
            "matchComputed": obj.get("matchComputed"),
            "displayName": obj.get("displayName"),
            "dbName": obj.get("dbName"),
            "lastIndexationInfos": LibItemIndexationInfos.from_dict(obj["lastIndexationInfos"]) if obj.get("lastIndexationInfos") is not None else None,
            "ownerFirstName": obj.get("ownerFirstName"),
            "ownerLastName": obj.get("ownerLastName"),
            "ownerEmail": obj.get("ownerEmail"),
            "ownerAvatarUrl": obj.get("ownerAvatarUrl"),
            "providerName": obj.get("providerName"),
            "additionalInfo": obj.get("additionalInfo"),
            "description": obj.get("description"),
            "authors": obj.get("authors"),
            "title": obj.get("title"),
            "additionalInfos": obj.get("additionalInfos"),
            "type": obj.get("type")
        })
        return _obj


