# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExpectedAnswerTypeDto(BaseModel):
    """
    ExpectedAnswerTypeDto
    """ # noqa: E501
    data_type: Optional[StrictStr] = Field(default=None, alias="dataType")
    multi_valued: Optional[StrictBool] = Field(default=None, alias="multiValued")
    enum_values: Optional[List[StrictStr]] = Field(default=None, description="List of possible values for enum types", alias="enumValues")
    enum_colors: Optional[Dict[str, StrictStr]] = Field(default=None, description="Map of enum values to their associated colors", alias="enumColors")
    enum_suggestions_enabled: Optional[StrictBool] = Field(default=None, alias="enumSuggestionsEnabled")
    rejected_enum_values: Optional[List[StrictStr]] = Field(default=None, alias="rejectedEnumValues")
    date_format: Optional[StrictStr] = Field(default=None, alias="dateFormat")
    decimal_precision: Optional[StrictStr] = Field(default=None, alias="decimalPrecision")
    __properties: ClassVar[List[str]] = ["dataType", "multiValued", "enumValues", "enumColors", "enumSuggestionsEnabled", "rejectedEnumValues", "dateFormat", "decimalPrecision"]

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STRING', 'INT', 'FLOAT', 'BOOL', 'DATE', 'ENUM', 'UNRECOGNIZED']):
            raise ValueError("must be one of enum values ('STRING', 'INT', 'FLOAT', 'BOOL', 'DATE', 'ENUM', 'UNRECOGNIZED')")
        return value

    @field_validator('date_format')
    def date_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ISO', 'EUR', 'US']):
            raise ValueError("must be one of enum values ('ISO', 'EUR', 'US')")
        return value

    @field_validator('decimal_precision')
    def decimal_precision_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ZERO_DECIMALS', 'ONE_DECIMAL', 'TWO_DECIMALS', 'THREE_DECIMALS', 'FOUR_DECIMALS', 'FIVE_DECIMALS', 'UNRECOGNIZED']):
            raise ValueError("must be one of enum values ('ZERO_DECIMALS', 'ONE_DECIMAL', 'TWO_DECIMALS', 'THREE_DECIMALS', 'FOUR_DECIMALS', 'FIVE_DECIMALS', 'UNRECOGNIZED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExpectedAnswerTypeDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExpectedAnswerTypeDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataType": obj.get("dataType"),
            "multiValued": obj.get("multiValued"),
            "enumValues": obj.get("enumValues"),
            "enumColors": obj.get("enumColors"),
            "enumSuggestionsEnabled": obj.get("enumSuggestionsEnabled"),
            "rejectedEnumValues": obj.get("rejectedEnumValues"),
            "dateFormat": obj.get("dateFormat"),
            "decimalPrecision": obj.get("decimalPrecision")
        })
        return _obj


