# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.fs_provider_external_config import FSProviderExternalConfig
from biolevate_client.models.policy_id_external import PolicyIdExternal
from biolevate_client.models.provider_id_external import ProviderIdExternal
from biolevate_client.models.user_id_external import UserIdExternal
from typing import Optional, Set
from typing_extensions import Self

class FSProviderExternal(BaseModel):
    """
    FSProviderExternal
    """ # noqa: E501
    id: Optional[ProviderIdExternal] = None
    created_time: Optional[StrictInt] = Field(default=None, alias="createdTime")
    owner: Optional[UserIdExternal] = None
    policy: Optional[PolicyIdExternal] = None
    name: Optional[StrictStr] = None
    icon: Optional[StrictStr] = None
    config: Optional[FSProviderExternalConfig] = None
    type: Optional[StrictStr] = None
    system: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "createdTime", "owner", "policy", "name", "icon", "config", "type", "system"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LOCAL', 'SHAREPOINT_ONLINE', 'S3', 'LEANEAR', 'AZURE', 'GCS', 'SFTP']):
            raise ValueError("must be one of enum values ('LOCAL', 'SHAREPOINT_ONLINE', 'S3', 'LEANEAR', 'AZURE', 'GCS', 'SFTP')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FSProviderExternal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FSProviderExternal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": ProviderIdExternal.from_dict(obj["id"]) if obj.get("id") is not None else None,
            "createdTime": obj.get("createdTime"),
            "owner": UserIdExternal.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "policy": PolicyIdExternal.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "name": obj.get("name"),
            "icon": obj.get("icon"),
            "config": FSProviderExternalConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "type": obj.get("type"),
            "system": obj.get("system")
        })
        return _obj


