# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from biolevate_client.models.fs_provider_azure_config_external import FSProviderAzureConfigExternal
from biolevate_client.models.fs_provider_gcs_config_external import FSProviderGCSConfigExternal
from biolevate_client.models.fs_provider_leanear_config_external import FSProviderLeanearConfigExternal
from biolevate_client.models.fs_provider_local_config_external import FSProviderLocalConfigExternal
from biolevate_client.models.fs_provider_s3_config_external import FSProviderS3ConfigExternal
from biolevate_client.models.fs_provider_sharepoint_online_config_external import FSProviderSharepointOnlineConfigExternal
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FSPROVIDEREXTERNALCONFIG_ONE_OF_SCHEMAS = ["FSProviderAzureConfigExternal", "FSProviderGCSConfigExternal", "FSProviderLeanearConfigExternal", "FSProviderLocalConfigExternal", "FSProviderS3ConfigExternal", "FSProviderSharepointOnlineConfigExternal"]

class FSProviderExternalConfig(BaseModel):
    """
    FSProviderExternalConfig
    """
    # data type: FSProviderAzureConfigExternal
    oneof_schema_1_validator: Optional[FSProviderAzureConfigExternal] = None
    # data type: FSProviderGCSConfigExternal
    oneof_schema_2_validator: Optional[FSProviderGCSConfigExternal] = None
    # data type: FSProviderLeanearConfigExternal
    oneof_schema_3_validator: Optional[FSProviderLeanearConfigExternal] = None
    # data type: FSProviderLocalConfigExternal
    oneof_schema_4_validator: Optional[FSProviderLocalConfigExternal] = None
    # data type: FSProviderS3ConfigExternal
    oneof_schema_5_validator: Optional[FSProviderS3ConfigExternal] = None
    # data type: FSProviderSharepointOnlineConfigExternal
    oneof_schema_6_validator: Optional[FSProviderSharepointOnlineConfigExternal] = None
    actual_instance: Optional[Union[FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal]] = None
    one_of_schemas: Set[str] = { "FSProviderAzureConfigExternal", "FSProviderGCSConfigExternal", "FSProviderLeanearConfigExternal", "FSProviderLocalConfigExternal", "FSProviderS3ConfigExternal", "FSProviderSharepointOnlineConfigExternal" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FSProviderExternalConfig.model_construct()
        error_messages = []
        match = 0
        # validate data type: FSProviderAzureConfigExternal
        if not isinstance(v, FSProviderAzureConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderAzureConfigExternal`")
        else:
            match += 1
        # validate data type: FSProviderGCSConfigExternal
        if not isinstance(v, FSProviderGCSConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderGCSConfigExternal`")
        else:
            match += 1
        # validate data type: FSProviderLeanearConfigExternal
        if not isinstance(v, FSProviderLeanearConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderLeanearConfigExternal`")
        else:
            match += 1
        # validate data type: FSProviderLocalConfigExternal
        if not isinstance(v, FSProviderLocalConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderLocalConfigExternal`")
        else:
            match += 1
        # validate data type: FSProviderS3ConfigExternal
        if not isinstance(v, FSProviderS3ConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderS3ConfigExternal`")
        else:
            match += 1
        # validate data type: FSProviderSharepointOnlineConfigExternal
        if not isinstance(v, FSProviderSharepointOnlineConfigExternal):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FSProviderSharepointOnlineConfigExternal`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FSProviderExternalConfig with oneOf schemas: FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FSProviderExternalConfig with oneOf schemas: FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FSProviderAzureConfigExternal
        try:
            instance.actual_instance = FSProviderAzureConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FSProviderGCSConfigExternal
        try:
            instance.actual_instance = FSProviderGCSConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FSProviderLeanearConfigExternal
        try:
            instance.actual_instance = FSProviderLeanearConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FSProviderLocalConfigExternal
        try:
            instance.actual_instance = FSProviderLocalConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FSProviderS3ConfigExternal
        try:
            instance.actual_instance = FSProviderS3ConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FSProviderSharepointOnlineConfigExternal
        try:
            instance.actual_instance = FSProviderSharepointOnlineConfigExternal.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FSProviderExternalConfig with oneOf schemas: FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FSProviderExternalConfig with oneOf schemas: FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


