# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from biolevate_client.models.fs_provider_azure_config_external import FSProviderAzureConfigExternal
    from biolevate_client.models.fs_provider_gcs_config_external import FSProviderGCSConfigExternal
    from biolevate_client.models.fs_provider_leanear_config_external import FSProviderLeanearConfigExternal
    from biolevate_client.models.fs_provider_local_config_external import FSProviderLocalConfigExternal
    from biolevate_client.models.fs_provider_s3_config_external import FSProviderS3ConfigExternal
    from biolevate_client.models.fs_provider_sharepoint_online_config_external import FSProviderSharepointOnlineConfigExternal

class FSProviderConfigurationExternal(BaseModel):
    """
    FSProviderConfigurationExternal
    """ # noqa: E501
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['LOCAL', 'SHAREPOINT_ONLINE', 'S3', 'LEANEAR', 'AZURE', 'GCS']):
            raise ValueError("must be one of enum values ('LOCAL', 'SHAREPOINT_ONLINE', 'S3', 'LEANEAR', 'AZURE', 'GCS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = 'type'

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'AZURE': 'FSProviderAzureConfigExternal','GCS': 'FSProviderGCSConfigExternal','LEANEAR': 'FSProviderLeanearConfigExternal','LOCAL': 'FSProviderLocalConfigExternal','S3': 'FSProviderS3ConfigExternal','SHAREPOINT_ONLINE': 'FSProviderSharepointOnlineConfigExternal'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal]]:
        """Create an instance of FSProviderConfigurationExternal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[FSProviderAzureConfigExternal, FSProviderGCSConfigExternal, FSProviderLeanearConfigExternal, FSProviderLocalConfigExternal, FSProviderS3ConfigExternal, FSProviderSharepointOnlineConfigExternal]]:
        """Create an instance of FSProviderConfigurationExternal from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'FSProviderAzureConfigExternal':
            return import_module("biolevate_client.models.fs_provider_azure_config_external").FSProviderAzureConfigExternal.from_dict(obj)
        if object_type ==  'FSProviderGCSConfigExternal':
            return import_module("biolevate_client.models.fs_provider_gcs_config_external").FSProviderGCSConfigExternal.from_dict(obj)
        if object_type ==  'FSProviderLeanearConfigExternal':
            return import_module("biolevate_client.models.fs_provider_leanear_config_external").FSProviderLeanearConfigExternal.from_dict(obj)
        if object_type ==  'FSProviderLocalConfigExternal':
            return import_module("biolevate_client.models.fs_provider_local_config_external").FSProviderLocalConfigExternal.from_dict(obj)
        if object_type ==  'FSProviderS3ConfigExternal':
            return import_module("biolevate_client.models.fs_provider_s3_config_external").FSProviderS3ConfigExternal.from_dict(obj)
        if object_type ==  'FSProviderSharepointOnlineConfigExternal':
            return import_module("biolevate_client.models.fs_provider_sharepoint_online_config_external").FSProviderSharepointOnlineConfigExternal.from_dict(obj)

        raise ValueError("FSProviderConfigurationExternal failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


