# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobStatistics(BaseModel):
    """
    JobStatistics
    """ # noqa: E501
    sources_queried: Optional[StrictInt] = Field(default=None, alias="sourcesQueried")
    sources_matched_locally: Optional[StrictInt] = Field(default=None, alias="sourcesMatchedLocally")
    sources_matched_remotely: Optional[StrictInt] = Field(default=None, alias="sourcesMatchedRemotely")
    sources_unmatched: Optional[StrictInt] = Field(default=None, alias="sourcesUnmatched")
    remote_search_status: Optional[StrictStr] = Field(default=None, alias="remoteSearchStatus")
    total_file_matches: Optional[StrictInt] = Field(default=None, alias="totalFileMatches")
    total_metadata_only_matches: Optional[StrictInt] = Field(default=None, alias="totalMetadataOnlyMatches")
    errors_by_search_result_id: Optional[Dict[str, StrictStr]] = Field(default=None, alias="errorsBySearchResultId")
    __properties: ClassVar[List[str]] = ["sourcesQueried", "sourcesMatchedLocally", "sourcesMatchedRemotely", "sourcesUnmatched", "remoteSearchStatus", "totalFileMatches", "totalMetadataOnlyMatches", "errorsBySearchResultId"]

    @field_validator('remote_search_status')
    def remote_search_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['PENDING', 'RUNNING', 'PROGRESS', 'ABORTED', 'COMPLETED', 'FAILED', 'OUTDATED']):
            raise ValueError("must be one of enum values ('PENDING', 'RUNNING', 'PROGRESS', 'ABORTED', 'COMPLETED', 'FAILED', 'OUTDATED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourcesQueried": obj.get("sourcesQueried"),
            "sourcesMatchedLocally": obj.get("sourcesMatchedLocally"),
            "sourcesMatchedRemotely": obj.get("sourcesMatchedRemotely"),
            "sourcesUnmatched": obj.get("sourcesUnmatched"),
            "remoteSearchStatus": obj.get("remoteSearchStatus"),
            "totalFileMatches": obj.get("totalFileMatches"),
            "totalMetadataOnlyMatches": obj.get("totalMetadataOnlyMatches"),
            "errorsBySearchResultId": obj.get("errorsBySearchResultId")
        })
        return _obj


