# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProviderItem(BaseModel):
    """
    Provider item (file or folder)
    """ # noqa: E501
    provider_id: Optional[StrictStr] = Field(default=None, description="Provider ID", alias="providerId")
    name: Optional[StrictStr] = Field(default=None, description="Item name")
    path: Optional[StrictStr] = Field(default=None, description="Directory path")
    type: Optional[StrictStr] = Field(default=None, description="Item type")
    size: Optional[StrictInt] = Field(default=None, description="File size in bytes (null for folders)")
    extension: Optional[StrictStr] = Field(default=None, description="File extension (null for folders)")
    media_type: Optional[StrictStr] = Field(default=None, description="Media type (null for folders)", alias="mediaType")
    last_modified: Optional[StrictInt] = Field(default=None, description="Last modified timestamp in milliseconds", alias="lastModified")
    __properties: ClassVar[List[str]] = ["providerId", "name", "path", "type", "size", "extension", "mediaType", "lastModified"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['FILE', 'FOLDER']):
            raise ValueError("must be one of enum values ('FILE', 'FOLDER')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "providerId": obj.get("providerId"),
            "name": obj.get("name"),
            "path": obj.get("path"),
            "type": obj.get("type"),
            "size": obj.get("size"),
            "extension": obj.get("extension"),
            "mediaType": obj.get("mediaType"),
            "lastModified": obj.get("lastModified")
        })
        return _obj


