# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from biolevate_client.models.file_match import FileMatch
from biolevate_client.models.metadata_only_match import MetadataOnlyMatch
from biolevate_client.models.source_identifiers import SourceIdentifiers
from typing import Optional, Set
from typing_extensions import Self

class SourceMatches(BaseModel):
    """
    SourceMatches
    """ # noqa: E501
    source: Optional[SourceIdentifiers] = None
    files: Optional[List[FileMatch]] = None
    metadata_only: Optional[List[MetadataOnlyMatch]] = Field(default=None, alias="metadataOnly")
    __properties: ClassVar[List[str]] = ["source", "files", "metadataOnly"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SourceMatches from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in metadata_only (list)
        _items = []
        if self.metadata_only:
            for _item_metadata_only in self.metadata_only:
                if _item_metadata_only:
                    _items.append(_item_metadata_only.to_dict())
            _dict['metadataOnly'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SourceMatches from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": SourceIdentifiers.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "files": [FileMatch.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None,
            "metadataOnly": [MetadataOnlyMatch.from_dict(_item) for _item in obj["metadataOnly"]] if obj.get("metadataOnly") is not None else None
        })
        return _obj


