# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.providers_api import ProvidersApi


class TestProvidersApi(unittest.IsolatedAsyncioTestCase):
    """ProvidersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProvidersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_provider(self) -> None:
        """Test case for get_provider

        Get a provider
        """
        pass

    async def test_list_providers(self) -> None:
        """Test case for list_providers

        List providers
        """
        pass


if __name__ == '__main__':
    unittest.main()
