# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.agent_completion_config import AgentCompletionConfig

class TestAgentCompletionConfig(unittest.TestCase):
    """AgentCompletionConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCompletionConfig:
        """Test AgentCompletionConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentCompletionConfig`
        """
        model = AgentCompletionConfig()
        if include_optional:
            return AgentCompletionConfig(
                model = 'BALANCED',
                temperature = 0.7,
                max_completion_tokens = 2048
            )
        else:
            return AgentCompletionConfig(
        )
        """

    def testAgentCompletionConfig(self):
        """Test AgentCompletionConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
