# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.create_file_request import CreateFileRequest

class TestCreateFileRequest(unittest.TestCase):
    """CreateFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFileRequest:
        """Test CreateFileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFileRequest`
        """
        model = CreateFileRequest()
        if include_optional:
            return CreateFileRequest(
                provider_id = '01a91a21-3136-4094-96da-ded4dce3824f',
                path = 'documents/',
                name = 'report.pdf'
            )
        else:
            return CreateFileRequest(
                provider_id = '01a91a21-3136-4094-96da-ded4dce3824f',
                path = 'documents/',
                name = 'report.pdf',
        )
        """

    def testCreateFileRequest(self):
        """Test CreateFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
