# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.job_statistics import JobStatistics

class TestJobStatistics(unittest.TestCase):
    """JobStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobStatistics:
        """Test JobStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobStatistics`
        """
        model = JobStatistics()
        if include_optional:
            return JobStatistics(
                sources_queried = 56,
                sources_matched_locally = 56,
                sources_matched_remotely = 56,
                sources_unmatched = 56,
                remote_search_status = 'PENDING',
                total_file_matches = 56,
                total_metadata_only_matches = 56,
                errors_by_search_result_id = {
                    'key' : ''
                    }
            )
        else:
            return JobStatistics(
        )
        """

    def testJobStatistics(self):
        """Test JobStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
