# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.position_line_dto import PositionLineDto

class TestPositionLineDto(unittest.TestCase):
    """PositionLineDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionLineDto:
        """Test PositionLineDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionLineDto`
        """
        model = PositionLineDto()
        if include_optional:
            return PositionLineDto(
                line_number = 56,
                column_index_start = 56,
                column_index_stop = 56
            )
        else:
            return PositionLineDto(
        )
        """

    def testPositionLineDto(self):
        """Test PositionLineDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
