# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.question_answering_api import QuestionAnsweringApi


class TestQuestionAnsweringApi(unittest.IsolatedAsyncioTestCase):
    """QuestionAnsweringApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = QuestionAnsweringApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_qa_job(self) -> None:
        """Test case for create_qa_job

        Create QA job
        """
        pass

    async def test_get_qa_job(self) -> None:
        """Test case for get_qa_job

        Get QA job
        """
        pass

    async def test_get_qa_job_annotations(self) -> None:
        """Test case for get_qa_job_annotations

        Get QA job annotations
        """
        pass

    async def test_get_qa_job_inputs(self) -> None:
        """Test case for get_qa_job_inputs

        Get QA job inputs
        """
        pass

    async def test_get_qa_job_outputs(self) -> None:
        """Test case for get_qa_job_outputs

        Get QA job outputs
        """
        pass

    async def test_list_qa_jobs(self) -> None:
        """Test case for list_qa_jobs

        List QA jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
