# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.agent_api import AgentApi


class TestAgentApi(unittest.IsolatedAsyncioTestCase):
    """AgentApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AgentApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_agent_job(self) -> None:
        """Test case for create_agent_job

        Create agent job
        """
        pass

    async def test_get_agent_job(self) -> None:
        """Test case for get_agent_job

        Get agent job
        """
        pass

    async def test_get_agent_job_annotations(self) -> None:
        """Test case for get_agent_job_annotations

        Get agent job annotations
        """
        pass

    async def test_get_agent_job_inputs(self) -> None:
        """Test case for get_agent_job_inputs

        Get agent job inputs
        """
        pass

    async def test_get_agent_job_outputs(self) -> None:
        """Test case for get_agent_job_outputs

        Get agent job outputs
        """
        pass

    async def test_list_agent_jobs(self) -> None:
        """Test case for list_agent_jobs

        List agent jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
