# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.last_merge_job_info import LastMergeJobInfo

class TestLastMergeJobInfo(unittest.TestCase):
    """LastMergeJobInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LastMergeJobInfo:
        """Test LastMergeJobInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LastMergeJobInfo`
        """
        model = LastMergeJobInfo()
        if include_optional:
            return LastMergeJobInfo(
                id = '',
                status = ''
            )
        else:
            return LastMergeJobInfo(
        )
        """

    def testLastMergeJobInfo(self):
        """Test LastMergeJobInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
