# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.add_file_to_collection_request import AddFileToCollectionRequest

class TestAddFileToCollectionRequest(unittest.TestCase):
    """AddFileToCollectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddFileToCollectionRequest:
        """Test AddFileToCollectionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddFileToCollectionRequest`
        """
        model = AddFileToCollectionRequest()
        if include_optional:
            return AddFileToCollectionRequest(
                file_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
            )
        else:
            return AddFileToCollectionRequest(
                file_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
        )
        """

    def testAddFileToCollectionRequest(self):
        """Test AddFileToCollectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
