# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.fs_provider_sftp_config_external import FSProviderSFTPConfigExternal

class TestFSProviderSFTPConfigExternal(unittest.TestCase):
    """FSProviderSFTPConfigExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FSProviderSFTPConfigExternal:
        """Test FSProviderSFTPConfigExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FSProviderSFTPConfigExternal`
        """
        model = FSProviderSFTPConfigExternal()
        if include_optional:
            return FSProviderSFTPConfigExternal(
                host = '',
                port = 56,
                username = '',
                root_path = '',
                allow_unknown_hosts = True,
                timeout_ms = 56
            )
        else:
            return FSProviderSFTPConfigExternal(
                host = '',
                port = 56,
                username = '',
        )
        """

    def testFSProviderSFTPConfigExternal(self):
        """Test FSProviderSFTPConfigExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
