# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.search_sources import SearchSources

class TestSearchSources(unittest.TestCase):
    """SearchSources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSources:
        """Test SearchSources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSources`
        """
        model = SearchSources()
        if include_optional:
            return SearchSources(
                source_identifiers = [
                    biolevate_client.models.source_identifiers.SourceIdentifiers(
                        doi = '', 
                        id = '', 
                        open_access_id = '', )
                    ]
            )
        else:
            return SearchSources(
        )
        """

    def testSearchSources(self):
        """Test SearchSources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
