# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.elise_document_statement_all_of_positions import EliseDocumentStatementAllOfPositions

class TestEliseDocumentStatementAllOfPositions(unittest.TestCase):
    """EliseDocumentStatementAllOfPositions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EliseDocumentStatementAllOfPositions:
        """Test EliseDocumentStatementAllOfPositions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EliseDocumentStatementAllOfPositions`
        """
        model = EliseDocumentStatementAllOfPositions()
        if include_optional:
            return EliseDocumentStatementAllOfPositions(
                type = 'BBOX',
                bbox = biolevate_client.models.bbox_dto.BboxDto(
                    x0 = 1.337, 
                    y0 = 1.337, 
                    x1 = 1.337, 
                    y1 = 1.337, ),
                page_number = 56,
                sheet_name = '',
                row = 56,
                col = 56,
                line_number = 56,
                column_index_start = 56,
                column_index_stop = 56
            )
        else:
            return EliseDocumentStatementAllOfPositions(
        )
        """

    def testEliseDocumentStatementAllOfPositions(self):
        """Test EliseDocumentStatementAllOfPositions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
