# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.page_data_elise_file_info import PageDataEliseFileInfo

class TestPageDataEliseFileInfo(unittest.TestCase):
    """PageDataEliseFileInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageDataEliseFileInfo:
        """Test PageDataEliseFileInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageDataEliseFileInfo`
        """
        model = PageDataEliseFileInfo()
        if include_optional:
            return PageDataEliseFileInfo(
                data = [
                    biolevate_client.models.elise_file_info.EliseFileInfo(
                        id = biolevate_client.models.file_id.FileId(
                            entity_type = 'POLICY', ), 
                        created_time = 56, 
                        owner = biolevate_client.models.user_id.UserId(), 
                        policy = biolevate_client.models.file_id.FileId(
                            entity_type = 'POLICY', ), 
                        provider_id = , 
                        name = '', 
                        path = '', 
                        size = 56, 
                        checksum = '', 
                        media_type = '', 
                        extension = '', 
                        indexed = True, 
                        match_computed = True, 
                        display_name = '', 
                        db_name = '', 
                        last_indexation_infos = biolevate_client.models.lib_item_indexation_infos.LibItemIndexationInfos(
                            status = 'SUCCESS', 
                            error_message = '', 
                            error_traceback = '', ), 
                        owner_first_name = '', 
                        owner_last_name = '', 
                        owner_email = '', 
                        owner_avatar_url = '', 
                        provider_name = '', 
                        additional_info = biolevate_client.models.additional_info.additionalInfo(), 
                        description = '', 
                        authors = '', 
                        title = '', 
                        additional_infos = null, 
                        type = 'FILE', )
                    ],
                total_pages = 56,
                total_elements = 56,
                has_next = True
            )
        else:
            return PageDataEliseFileInfo(
        )
        """

    def testPageDataEliseFileInfo(self):
        """Test PageDataEliseFileInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
