# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.extraction_api import ExtractionApi


class TestExtractionApi(unittest.IsolatedAsyncioTestCase):
    """ExtractionApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ExtractionApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_extraction_job(self) -> None:
        """Test case for create_extraction_job

        Create extraction job
        """
        pass

    async def test_get_extraction_job(self) -> None:
        """Test case for get_extraction_job

        Get extraction job
        """
        pass

    async def test_get_extraction_job_annotations(self) -> None:
        """Test case for get_extraction_job_annotations

        Get extraction job annotations
        """
        pass

    async def test_get_extraction_job_inputs(self) -> None:
        """Test case for get_extraction_job_inputs

        Get extraction job inputs
        """
        pass

    async def test_get_extraction_job_outputs(self) -> None:
        """Test case for get_extraction_job_outputs

        Get extraction job outputs
        """
        pass

    async def test_list_extraction_jobs(self) -> None:
        """Test case for list_extraction_jobs

        List extraction jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
