# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.mde_job_outputs import MDEJobOutputs

class TestMDEJobOutputs(unittest.TestCase):
    """MDEJobOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MDEJobOutputs:
        """Test MDEJobOutputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MDEJobOutputs`
        """
        model = MDEJobOutputs()
        if include_optional:
            return MDEJobOutputs(
                entity_extraction = biolevate_client.models.elise_entity_extraction_result.EliseEntityExtractionResult(
                    meta_id = '', 
                    meta = '', 
                    schema = biolevate_client.models.elise_entity_schema_input.EliseEntitySchemaInput(
                        name = '', 
                        columns = [
                            biolevate_client.models.elise_entity_column_input.EliseEntityColumnInput(
                                key = '', 
                                label = '', 
                                type = 'ENTITY_COLUMN_TYPE_UNSPECIFIED', 
                                role = 'ENTITY_COLUMN_ROLE_UNSPECIFIED', 
                                description = '', 
                                allowed_values = [
                                    ''
                                    ], 
                                is_row_key = True, )
                            ], ), 
                    rows = [
                        biolevate_client.models.elise_entity_row_result.EliseEntityRowResult(
                            cells = [
                                biolevate_client.models.elise_entity_cell_result.EliseEntityCellResult(
                                    column_key = '', 
                                    value = biolevate_client.models.value.value(), 
                                    explanation = '', 
                                    reference_ids = [
                                        biolevate_client.models.entity_id.EntityId(
                                            id = '', 
                                            entity_type = 'POLICY', )
                                        ], )
                                ], 
                            explanation = '', 
                            reference_ids = [
                                biolevate_client.models.entity_id.EntityId(
                                    id = '', 
                                    entity_type = 'POLICY', )
                                ], )
                        ], 
                    explanation = '', 
                    reference_ids = , )
            )
        else:
            return MDEJobOutputs(
        )
        """

    def testMDEJobOutputs(self):
        """Test MDEJobOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
