# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.page_data_elise_collection_info import PageDataEliseCollectionInfo

class TestPageDataEliseCollectionInfo(unittest.TestCase):
    """PageDataEliseCollectionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageDataEliseCollectionInfo:
        """Test PageDataEliseCollectionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageDataEliseCollectionInfo`
        """
        model = PageDataEliseCollectionInfo()
        if include_optional:
            return PageDataEliseCollectionInfo(
                data = [
                    biolevate_client.models.elise_collection_info.EliseCollectionInfo(
                        id = biolevate_client.models.file_id.FileId(
                            entity_type = 'POLICY', ), 
                        created_time = 56, 
                        owner = biolevate_client.models.user_id.UserId(), 
                        policy = biolevate_client.models.file_id.FileId(
                            entity_type = 'POLICY', ), 
                        name = '', 
                        description = '', 
                        icon = '', 
                        owner_first_name = '', 
                        owner_last_name = '', 
                        owner_email = '', 
                        owner_avatar_url = '', 
                        files_count = 56, 
                        derived_from_collection_id = , 
                        derived_from_collection_name = '', 
                        derived_from_view_id = , 
                        derived_from_view_name = '', 
                        chained = True, 
                        derived_to_collection_id = , 
                        derived_to_collection_name = '', )
                    ],
                total_pages = 56,
                total_elements = 56,
                has_next = True
            )
        else:
            return PageDataEliseCollectionInfo(
        )
        """

    def testPageDataEliseCollectionInfo(self):
        """Test PageDataEliseCollectionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
