# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.source_matches import SourceMatches

class TestSourceMatches(unittest.TestCase):
    """SourceMatches unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceMatches:
        """Test SourceMatches
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SourceMatches`
        """
        model = SourceMatches()
        if include_optional:
            return SourceMatches(
                source = biolevate_client.models.source_identifiers.SourceIdentifiers(
                    doi = '', 
                    id = '', 
                    open_access_id = '', ),
                files = [
                    biolevate_client.models.file_match.FileMatch(
                        file_id = '', 
                        provider_id = '', 
                        path = '', 
                        name = '', 
                        checksum = '', 
                        ontologies = [
                            biolevate_client.models.elise_ontology.EliseOntology(
                                concept_id = biolevate_client.models.entity_id.EntityId(
                                    id = '', 
                                    entity_type = 'POLICY', ), 
                                name = '', 
                                metas = {
                                    'key' : biolevate_client.models.elise_ontology_meta.EliseOntologyMeta(
                                        explanation = '', 
                                        annotation_ids = [
                                            biolevate_client.models.entity_id.EntityId(
                                                id = '', 
                                                entity_type = 'POLICY', )
                                            ], 
                                        meta_name = '', 
                                        meta_value = biolevate_client.models.meta_value.metaValue(), )
                                    }, )
                            ], )
                    ],
                metadata_only = [
                    biolevate_client.models.metadata_only_match.MetadataOnlyMatch(
                        search_result_id = '', 
                        ontologies = [
                            biolevate_client.models.elise_ontology.EliseOntology(
                                concept_id = biolevate_client.models.entity_id.EntityId(
                                    id = '', 
                                    entity_type = 'POLICY', ), 
                                name = '', 
                                metas = {
                                    'key' : biolevate_client.models.elise_ontology_meta.EliseOntologyMeta(
                                        explanation = '', 
                                        annotation_ids = [
                                            biolevate_client.models.entity_id.EntityId(
                                                id = '', 
                                                entity_type = 'POLICY', )
                                            ], 
                                        meta_name = '', 
                                        meta_value = biolevate_client.models.meta_value.metaValue(), )
                                    }, )
                            ], )
                    ]
            )
        else:
            return SourceMatches(
        )
        """

    def testSourceMatches(self):
        """Test SourceMatches"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
