# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.mde_job_inputs import MDEJobInputs

class TestMDEJobInputs(unittest.TestCase):
    """MDEJobInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MDEJobInputs:
        """Test MDEJobInputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MDEJobInputs`
        """
        model = MDEJobInputs()
        if include_optional:
            return MDEJobInputs(
                files = biolevate_client.models.files_input.FilesInput(
                    file_ids = [
                        ''
                        ], 
                    collection_ids = [
                        ''
                        ], ),
                var_schema = biolevate_client.models.elise_entity_schema_input.EliseEntitySchemaInput(
                    name = '', 
                    description = '', 
                    columns = [
                        biolevate_client.models.elise_entity_column_input.EliseEntityColumnInput(
                            key = '', 
                            label = '', 
                            type = 'ENTITY_COLUMN_TYPE_UNSPECIFIED', 
                            role = 'ENTITY_COLUMN_ROLE_UNSPECIFIED', 
                            description = '', 
                            allowed_values = [
                                ''
                                ], 
                            is_row_key = True, )
                        ], ),
                prompt = ''
            )
        else:
            return MDEJobInputs(
        )
        """

    def testMDEJobInputs(self):
        """Test MDEJobInputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
