# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.policy_id_external import PolicyIdExternal

class TestPolicyIdExternal(unittest.TestCase):
    """PolicyIdExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyIdExternal:
        """Test PolicyIdExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyIdExternal`
        """
        model = PolicyIdExternal()
        if include_optional:
            return PolicyIdExternal(
                id = '',
                entity_type = 'POLICY'
            )
        else:
            return PolicyIdExternal(
        )
        """

    def testPolicyIdExternal(self):
        """Test PolicyIdExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
