# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.metadata_only_match import MetadataOnlyMatch

class TestMetadataOnlyMatch(unittest.TestCase):
    """MetadataOnlyMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataOnlyMatch:
        """Test MetadataOnlyMatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataOnlyMatch`
        """
        model = MetadataOnlyMatch()
        if include_optional:
            return MetadataOnlyMatch(
                search_result_id = '',
                ontologies = [
                    biolevate_client.models.elise_ontology.EliseOntology(
                        concept_id = biolevate_client.models.entity_id.EntityId(
                            id = '', 
                            entity_type = 'POLICY', ), 
                        name = '', 
                        metas = {
                            'key' : biolevate_client.models.elise_ontology_meta.EliseOntologyMeta(
                                explanation = '', 
                                annotation_ids = [
                                    biolevate_client.models.entity_id.EntityId(
                                        id = '', 
                                        entity_type = 'POLICY', )
                                    ], 
                                meta_name = '', 
                                meta_value = biolevate_client.models.meta_value.metaValue(), )
                            }, )
                    ]
            )
        else:
            return MetadataOnlyMatch(
        )
        """

    def testMetadataOnlyMatch(self):
        """Test MetadataOnlyMatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
