# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.create_agent_request import CreateAgentRequest

class TestCreateAgentRequest(unittest.TestCase):
    """CreateAgentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAgentRequest:
        """Test CreateAgentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAgentRequest`
        """
        model = CreateAgentRequest()
        if include_optional:
            return CreateAgentRequest(
                message = 'Summarize the attached report and list the main risks.',
                messages = [
                    biolevate_client.models.agent_input.AgentInput(
                        role = 'USER', 
                        content = 'Summarize the attached report.', )
                    ],
                files = biolevate_client.models.files_input.FilesInput(
                    file_ids = [
                        ''
                        ], 
                    collection_ids = [
                        ''
                        ], ),
                config = biolevate_client.models.job_launch_config.JobLaunchConfig(
                    skip_unindexed_files = False, ),
                history_input_valid = True,
                conversation_id_valid = True,
                output_model_schema = None,
                completion_config = biolevate_client.models.agent_completion_config.AgentCompletionConfig(
                    model = 'BALANCED', 
                    temperature = 0.7, 
                    max_completion_tokens = 2048, ),
                max_iterations = 10,
                conversation_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
            )
        else:
            return CreateAgentRequest(
        )
        """

    def testCreateAgentRequest(self):
        """Test CreateAgentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
