# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.position_cell_dto import PositionCellDto

class TestPositionCellDto(unittest.TestCase):
    """PositionCellDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionCellDto:
        """Test PositionCellDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionCellDto`
        """
        model = PositionCellDto()
        if include_optional:
            return PositionCellDto(
                sheet_name = '',
                row = 56,
                col = 56
            )
        else:
            return PositionCellDto(
        )
        """

    def testPositionCellDto(self):
        """Test PositionCellDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
