# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.elise_annotation import EliseAnnotation

class TestEliseAnnotation(unittest.TestCase):
    """EliseAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EliseAnnotation:
        """Test EliseAnnotation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EliseAnnotation`
        """
        model = EliseAnnotation()
        if include_optional:
            return EliseAnnotation(
                id = biolevate_client.models.file_id.FileId(
                    id = '', 
                    entity_type = 'POLICY', ),
                created_time = 56,
                owner = biolevate_client.models.user_id.UserId(
                    id = '', ),
                space = biolevate_client.models.file_id.FileId(
                    id = '', 
                    entity_type = 'POLICY', ),
                data = None,
                type = 'DOCUMENT_STATEMENT',
                modified_time = 56,
                last_modifier = biolevate_client.models.user_id.UserId(
                    id = '', ),
                status = 'VALID'
            )
        else:
            return EliseAnnotation(
        )
        """

    def testEliseAnnotation(self):
        """Test EliseAnnotation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
