# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.agent_job_outputs import AgentJobOutputs

class TestAgentJobOutputs(unittest.TestCase):
    """AgentJobOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentJobOutputs:
        """Test AgentJobOutputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentJobOutputs`
        """
        model = AgentJobOutputs()
        if include_optional:
            return AgentJobOutputs(
                answer = biolevate_client.models.additional_info.additionalInfo(),
                explanation = '',
                reference_ids = [
                    ''
                    ]
            )
        else:
            return AgentJobOutputs(
        )
        """

    def testAgentJobOutputs(self):
        """Test AgentJobOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
