# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.upload_url_request import UploadUrlRequest

class TestUploadUrlRequest(unittest.TestCase):
    """UploadUrlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadUrlRequest:
        """Test UploadUrlRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadUrlRequest`
        """
        model = UploadUrlRequest()
        if include_optional:
            return UploadUrlRequest(
                path = '/reports/',
                file_name = 'document.pdf',
                size = 1048576,
                media_type = 'application/pdf'
            )
        else:
            return UploadUrlRequest(
                path = '/reports/',
                file_name = 'document.pdf',
        )
        """

    def testUploadUrlRequest(self):
        """Test UploadUrlRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
