# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.create_qa_request import CreateQARequest

class TestCreateQARequest(unittest.TestCase):
    """CreateQARequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateQARequest:
        """Test CreateQARequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateQARequest`
        """
        model = CreateQARequest()
        if include_optional:
            return CreateQARequest(
                files = biolevate_client.models.files_input.FilesInput(
                    file_ids = [
                        ''
                        ], 
                    collection_ids = [
                        ''
                        ], ),
                questions = [
                    biolevate_client.models.elise_question_input.EliseQuestionInput(
                        id = '', 
                        question = '', 
                        answer_type = biolevate_client.models.expected_answer_type_dto.ExpectedAnswerTypeDto(
                            data_type = 'STRING', 
                            multi_valued = True, 
                            enum_values = [
                                ''
                                ], 
                            enum_colors = {
                                'key' : ''
                                }, 
                            enum_suggestions_enabled = True, 
                            rejected_enum_values = [
                                ''
                                ], 
                            date_format = 'ISO', 
                            decimal_precision = 'ZERO_DECIMALS', ), 
                        guidelines = '', 
                        expected_answer = '', 
                        input_question_ids = [
                            ''
                            ], )
                    ]
            )
        else:
            return CreateQARequest(
        )
        """

    def testCreateQARequest(self):
        """Test CreateQARequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
