# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.find_similar_files_api import FindSimilarFilesApi


class TestFindSimilarFilesApi(unittest.IsolatedAsyncioTestCase):
    """FindSimilarFilesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FindSimilarFilesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_job(self) -> None:
        """Test case for create_job

        Create find-similar job
        """
        pass

    async def test_get_job(self) -> None:
        """Test case for get_job

        Get find-similar job
        """
        pass

    async def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List find-similar jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
