# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.list_items_response import ListItemsResponse

class TestListItemsResponse(unittest.TestCase):
    """ListItemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListItemsResponse:
        """Test ListItemsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListItemsResponse`
        """
        model = ListItemsResponse()
        if include_optional:
            return ListItemsResponse(
                items = [
                    biolevate_client.models.provider_item.ProviderItem(
                        provider_id = '550e8400-e29b-41d4-a716-446655440000', 
                        name = 'document.pdf', 
                        path = '/reports/', 
                        type = 'FILE', 
                        size = 1048576, 
                        extension = 'pdf', 
                        media_type = 'application/pdf', 
                        last_modified = 1708123456789, )
                    ],
                next_cursor = ''
            )
        else:
            return ListItemsResponse(
        )
        """

    def testListItemsResponse(self):
        """Test ListItemsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
