# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.elise_full_document_statement import EliseFullDocumentStatement

class TestEliseFullDocumentStatement(unittest.TestCase):
    """EliseFullDocumentStatement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EliseFullDocumentStatement:
        """Test EliseFullDocumentStatement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EliseFullDocumentStatement`
        """
        model = EliseFullDocumentStatement()
        if include_optional:
            return EliseFullDocumentStatement(
                document_name = '',
                document_id = ''
            )
        else:
            return EliseFullDocumentStatement(
        )
        """

    def testEliseFullDocumentStatement(self):
        """Test EliseFullDocumentStatement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
