# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.page_data_job import PageDataJob

class TestPageDataJob(unittest.TestCase):
    """PageDataJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageDataJob:
        """Test PageDataJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageDataJob`
        """
        model = PageDataJob()
        if include_optional:
            return PageDataJob(
                data = [
                    biolevate_client.models.job.Job(
                        job_id = '', 
                        status = 'SUCCESS', 
                        task_type = '', 
                        created_time = 56, 
                        execution_time = 1.337, 
                        error_message = '', 
                        name = '', 
                        archived = True, )
                    ],
                total_pages = 56,
                total_elements = 56,
                has_next = True
            )
        else:
            return PageDataJob(
        )
        """

    def testPageDataJob(self):
        """Test PageDataJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
