# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.bbox_dto import BboxDto

class TestBboxDto(unittest.TestCase):
    """BboxDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BboxDto:
        """Test BboxDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BboxDto`
        """
        model = BboxDto()
        if include_optional:
            return BboxDto(
                x0 = 1.337,
                y0 = 1.337,
                x1 = 1.337,
                y1 = 1.337
            )
        else:
            return BboxDto(
        )
        """

    def testBboxDto(self):
        """Test BboxDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
