# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.fs_provider_azure_config_external import FSProviderAzureConfigExternal

class TestFSProviderAzureConfigExternal(unittest.TestCase):
    """FSProviderAzureConfigExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FSProviderAzureConfigExternal:
        """Test FSProviderAzureConfigExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FSProviderAzureConfigExternal`
        """
        model = FSProviderAzureConfigExternal()
        if include_optional:
            return FSProviderAzureConfigExternal(
                container_name = '',
                account_name = '',
                use_workload_identity = True,
                workload_identity_enabled = True,
                connection_string_enabled = True,
                endpoint_url = ''
            )
        else:
            return FSProviderAzureConfigExternal(
                container_name = '',
        )
        """

    def testFSProviderAzureConfigExternal(self):
        """Test FSProviderAzureConfigExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
