# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.collection_view_id import CollectionViewId

class TestCollectionViewId(unittest.TestCase):
    """CollectionViewId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionViewId:
        """Test CollectionViewId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionViewId`
        """
        model = CollectionViewId()
        if include_optional:
            return CollectionViewId(
                id = '',
                entity_type = 'POLICY'
            )
        else:
            return CollectionViewId(
        )
        """

    def testCollectionViewId(self):
        """Test CollectionViewId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
