# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.IsolatedAsyncioTestCase):
    """CollectionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CollectionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_file_to_collection(self) -> None:
        """Test case for add_file_to_collection

        Add file to collection
        """
        pass

    async def test_create_collection(self) -> None:
        """Test case for create_collection

        Create a collection
        """
        pass

    async def test_delete_collection(self) -> None:
        """Test case for delete_collection

        Delete a collection
        """
        pass

    async def test_get_collection(self) -> None:
        """Test case for get_collection

        Get a collection
        """
        pass

    async def test_list_collection_files(self) -> None:
        """Test case for list_collection_files

        List files in collection
        """
        pass

    async def test_list_collections(self) -> None:
        """Test case for list_collections

        List collections
        """
        pass

    async def test_remove_file_from_collection(self) -> None:
        """Test case for remove_file_from_collection

        Remove file from collection
        """
        pass

    async def test_update_collection(self) -> None:
        """Test case for update_collection

        Update a collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
