# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.agent_job_inputs import AgentJobInputs

class TestAgentJobInputs(unittest.TestCase):
    """AgentJobInputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentJobInputs:
        """Test AgentJobInputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentJobInputs`
        """
        model = AgentJobInputs()
        if include_optional:
            return AgentJobInputs(
                message = '',
                messages = [
                    biolevate_client.models.agent_input.AgentInput(
                        role = 'USER', 
                        content = 'Summarize the attached report.', )
                    ],
                files = biolevate_client.models.files_input.FilesInput(
                    file_ids = [
                        ''
                        ], 
                    collection_ids = [
                        ''
                        ], ),
                output_model_schema = biolevate_client.models.additional_info.additionalInfo(),
                completion_config = biolevate_client.models.agent_completion_config.AgentCompletionConfig(
                    model = 'BALANCED', 
                    temperature = 0.7, 
                    max_completion_tokens = 2048, ),
                max_iterations = 56,
                conversation_id = ''
            )
        else:
            return AgentJobInputs(
        )
        """

    def testAgentJobInputs(self):
        """Test AgentJobInputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
