# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.qa_job_outputs import QAJobOutputs

class TestQAJobOutputs(unittest.TestCase):
    """QAJobOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QAJobOutputs:
        """Test QAJobOutputs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QAJobOutputs`
        """
        model = QAJobOutputs()
        if include_optional:
            return QAJobOutputs(
                results = [
                    biolevate_client.models.elise_qa_result.EliseQAResult(
                        explanation = '', 
                        sourced_content = '', 
                        reference_ids = [
                            biolevate_client.models.file_id.FileId(
                                id = '', 
                                entity_type = 'POLICY', )
                            ], 
                        question = '', 
                        expected_answer = '', 
                        validity_explaination = '', 
                        input_question_ids = [
                            ''
                            ], 
                        answer_validity = 1.337, 
                        raw_value = '', )
                    ]
            )
        else:
            return QAJobOutputs(
        )
        """

    def testQAJobOutputs(self):
        """Test QAJobOutputs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
