# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.fs_provider_sharepoint_online_config_external import FSProviderSharepointOnlineConfigExternal

class TestFSProviderSharepointOnlineConfigExternal(unittest.TestCase):
    """FSProviderSharepointOnlineConfigExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FSProviderSharepointOnlineConfigExternal:
        """Test FSProviderSharepointOnlineConfigExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FSProviderSharepointOnlineConfigExternal`
        """
        model = FSProviderSharepointOnlineConfigExternal()
        if include_optional:
            return FSProviderSharepointOnlineConfigExternal(
                site_url = '',
                document_library = '',
                tenant_id = ''
            )
        else:
            return FSProviderSharepointOnlineConfigExternal(
                site_url = '',
                document_library = '',
                tenant_id = '',
        )
        """

    def testFSProviderSharepointOnlineConfigExternal(self):
        """Test FSProviderSharepointOnlineConfigExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
