# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.page_data_find_similar_api_job_dto import PageDataFindSimilarApiJobDto

class TestPageDataFindSimilarApiJobDto(unittest.TestCase):
    """PageDataFindSimilarApiJobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageDataFindSimilarApiJobDto:
        """Test PageDataFindSimilarApiJobDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageDataFindSimilarApiJobDto`
        """
        model = PageDataFindSimilarApiJobDto()
        if include_optional:
            return PageDataFindSimilarApiJobDto(
                data = [
                    biolevate_client.models.find_similar_api_job_dto.FindSimilarApiJobDto(
                        job_id = '', 
                        status = 'PENDING', 
                        created_time = 56, 
                        modified_time = 56, 
                        execution_time_ms = 56, 
                        error_message = '', 
                        sources = biolevate_client.models.search_sources.SearchSources(
                            source_identifiers = [
                                biolevate_client.models.source_identifiers.SourceIdentifiers(
                                    doi = '', 
                                    id = '', 
                                    open_access_id = '', )
                                ], ), 
                        result = [
                            biolevate_client.models.source_matches.SourceMatches(
                                source = biolevate_client.models.source_identifiers.SourceIdentifiers(
                                    doi = '', 
                                    id = '', 
                                    open_access_id = '', ), 
                                files = [
                                    biolevate_client.models.file_match.FileMatch(
                                        file_id = '', 
                                        provider_id = '', 
                                        path = '', 
                                        name = '', 
                                        checksum = '', 
                                        ontologies = [
                                            biolevate_client.models.elise_ontology.EliseOntology(
                                                concept_id = biolevate_client.models.entity_id.EntityId(
                                                    id = '', 
                                                    entity_type = 'POLICY', ), 
                                                name = '', 
                                                metas = {
                                                    'key' : biolevate_client.models.elise_ontology_meta.EliseOntologyMeta(
                                                        explanation = '', 
                                                        annotation_ids = [
                                                            biolevate_client.models.entity_id.EntityId(
                                                                id = '', 
                                                                entity_type = 'POLICY', )
                                                            ], 
                                                        meta_name = '', 
                                                        meta_value = biolevate_client.models.meta_value.metaValue(), )
                                                    }, )
                                            ], )
                                    ], 
                                metadata_only = [
                                    biolevate_client.models.metadata_only_match.MetadataOnlyMatch(
                                        search_result_id = '', )
                                    ], )
                            ], 
                        statistics = biolevate_client.models.job_statistics.JobStatistics(
                            sources_queried = 56, 
                            sources_matched_locally = 56, 
                            sources_matched_remotely = 56, 
                            sources_unmatched = 56, 
                            remote_search_status = 'PENDING', 
                            total_file_matches = 56, 
                            total_metadata_only_matches = 56, 
                            errors_by_search_result_id = {
                                'key' : ''
                                }, ), )
                    ],
                total_pages = 56,
                total_elements = 56,
                has_next = True
            )
        else:
            return PageDataFindSimilarApiJobDto(
        )
        """

    def testPageDataFindSimilarApiJobDto(self):
        """Test PageDataFindSimilarApiJobDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
