# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.models.fs_provider_s3_config_external import FSProviderS3ConfigExternal

class TestFSProviderS3ConfigExternal(unittest.TestCase):
    """FSProviderS3ConfigExternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FSProviderS3ConfigExternal:
        """Test FSProviderS3ConfigExternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FSProviderS3ConfigExternal`
        """
        model = FSProviderS3ConfigExternal()
        if include_optional:
            return FSProviderS3ConfigExternal(
                bucket_name = '',
                region = ''
            )
        else:
            return FSProviderS3ConfigExternal(
                bucket_name = '',
                region = '',
        )
        """

    def testFSProviderS3ConfigExternal(self):
        """Test FSProviderS3ConfigExternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
