# coding: utf-8

"""
    Biolevate API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biolevate_client.api.provider_items_api import ProviderItemsApi


class TestProviderItemsApi(unittest.IsolatedAsyncioTestCase):
    """ProviderItemsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProviderItemsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_confirm_upload(self) -> None:
        """Test case for confirm_upload

        Confirm presigned upload
        """
        pass

    async def test_delete_item(self) -> None:
        """Test case for delete_item

        Delete item
        """
        pass

    async def test_get_download_url(self) -> None:
        """Test case for get_download_url

        Get download URL
        """
        pass

    async def test_get_file_content(self) -> None:
        """Test case for get_file_content

        Get file content
        """
        pass

    async def test_get_upload_url(self) -> None:
        """Test case for get_upload_url

        Get presigned upload URL
        """
        pass

    async def test_list_items(self) -> None:
        """Test case for list_items

        List items
        """
        pass

    async def test_rename_item(self) -> None:
        """Test case for rename_item

        Rename item
        """
        pass

    async def test_upload_file(self) -> None:
        """Test case for upload_file

        Create folder
        """
        pass


if __name__ == '__main__':
    unittest.main()
